"site_name": "AgriPipe"
"site_description": "Data pipeline"
"site_author": "Francesco"
"repo_url": "https://github.com/francesco5252/agripipe"

"theme":
  "name": "material"
  "palette":
    - "media": "(prefers-color-scheme: light)"
      "scheme": "default"
      "primary": "green"
      "accent": "light green"
    - "media": "(prefers-color-scheme: dark)"
      "scheme": "slate"
      "primary": "green"
      "accent": "light green"

"plugins":
  - "search"
  - "mkdocstrings":
      "handlers":
        "python":
          "paths": ["src"]

"nav":
  - "Home": "index.md"
  - "Guida": "getting-started.md"
